### ISSUE TITLE
Delete this repository.

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Test-Assets#1]
We should delete this repository:
- Assets don't belong on git.
- We'll want to get rid of MD3 support eventually.
- I don't think this was used by anyone, ever.
- Even if it was used by someone, we could just put a tarball on some webserver instead. This repo isn't going to receive new commits.

**Comment by DolceTriade** [comment]
It was used by me :(

**Comment by Viech** [comment]
Is that a "don't delete" or a "we can just put them in a tarball", @DolceTriade?

**Comment by DolceTriade** [comment]
We can put in a tarball.

**Comment by Viech** [comment]
Put a copy at http://dl.unvanquished.net/test-assets.zip and will delete the repository within the next days.

**Comment by Viech** [comment]
*All the planning charts and demolition orders have been on display at your local planning department in Alpha Centauri for one of your Earth years, so you’ve had plenty of time to lodge any formal complaint and it’s far too late to start making a fuss about it now.*
